---
- name: patching rhel & Ubuntu vms 
  hosts: localhost

  tasks:
    - name: Patching Redhat server
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Patching Ubuntu servers
      apt:
        name: "*"
        state: latest
      when: ansible_os_family == "Debian"
