---
- name: patching rhel & Ubuntu vms
  hosts: all

  tasks:
    - name: Patching Redhat servers
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Patching Ubuntu servers
      apt:
        name: "*"
        state: latest
      when: ansible_os_family == "Debian"
